import Content from "../shared/Content"
import PageHeader from "../shared/PageHeader"
import Video from './../../assets/video/1084666594-preview.mp4'

const DanceCurriculumPage = () => {
    return (
        <div id="dance-curriculum-page">
            <PageHeader title="Dance Curriculum" video={Video} />
            <Content page="dance-curriculum">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat.</p> 
                <h3>Hip Hop Dance</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Breakdance</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Locking</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Popping</h3>
                <h3>Krumping</h3>
                
                <h3>Boogaloo/Electric Boogaloo</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Waacking</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Electro Dance</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>House Dance</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Funk</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>African Dance</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Caribbean Dance</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Freesyle</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Yoga</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Calisthenics</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Team Work</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
                <h3>Showcase</h3>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi euismod ex sodales, commodo nunc pulvinar, tincidunt nulla. Quisque sit amet sem eros. Donec sit amet felis dolor. Ut eleifend consequat metus non condimentum. Vestibulum id luctus eros. Etiam sit amet tincidunt diam. Cras feugiat, metus nec fringilla pharetra, nisl mi dapibus mauris, quis commodo massa velit ac dolor. Vivamus eget velit et magna sollicitudin elementum a sit amet neque. Ut pellentesque enim non libero mollis consequat. Curabitur lacinia est sit amet nisl maximus fringilla. Praesent vitae velit quis leo sagittis fringilla non non nunc. Nulla at arcu dictum, vestibulum ante ut, suscipit orci. Nunc a felis suscipit lorem fringilla lobortis sit amet volutpat quam.</p>
            </Content>
        </div>
    )
}

export default DanceCurriculumPage